use ratatui::{
    layout::{Constraint, Direction, Layout, Rect},
    style::{Color, Modifier, Style},
    text::{Line, Span, Text},
    widgets::{Block, Borders, Paragraph},
    Frame,
};

use rusqlite::Connection;
use tui_textarea::{TextArea};

use sad_xml_sql::{Component, get_component_by_name};
use super::work_state::WorkState;


pub fn render_component_details_pane(
    frame: &mut Frame,
    _work_state: &mut WorkState,
    db_conn: &Connection,
    area: Rect,
    selected_item: String,
) {
    let component = get_component_by_name(db_conn, selected_item);

    let text = if let Ok(component) = component {
        let line_id = Line::from(vec![
            Span::styled(
                "id.....: ",
                Style::default().fg(Color::Black).bg(Color::Gray),
            ),
            Span::styled(
                format!("{} ", component.id),
                Style::default().fg(Color::Black).bg(Color::Gray),
            ),
        ]);
        let line_name = Line::from(vec![
            Span::styled(
                "name...: ",
                Style::default().fg(Color::Black).bg(Color::Gray),
            ),
            Span::styled(
                format!("{} ", component.name),
                Style::default().fg(Color::Black).bg(Color::Gray),
            ),
        ]);
        let line_purpose = Line::from(vec![
            Span::styled(
                "purpose: ",
                Style::default().fg(Color::Black).bg(Color::Gray),
            ),
            Span::styled(
                format!("{} ", component.purpose),
                Style::default().fg(Color::Black).bg(Color::Gray),
            ),
        ]);
        let line_summary = Line::from(vec![
            Span::styled(
                "summary: ",
                Style::default().fg(Color::Black).bg(Color::Gray),
            ),
            Span::styled(
                format!("{} ", component.summary),
                Style::default().fg(Color::Black).bg(Color::Gray),
            ),
        ]);
        Text::from(vec![line_id, line_name, line_purpose, line_summary])
    } else {
        Text::from("no data available for this component")
    };

    let paragraph = Paragraph::new(text).block(
        Block::default()
            .borders(Borders::ALL)
            .title("Component")
            .style(Style::default().bg(Color::DarkGray)),
    );
    frame.render_widget(paragraph, area);
}

/*
 Since TextArea can't be combined with anything else, then the label and input needs to be split
 into separate panes.
 So split the editor pane into two panes: one for the label and one for the input.
 and then each input is in its own row.

 First split the pane vertically into as many parts/rows as there are fields.
 Then render each row, with a fixed left(label) and right(input) part
*/
// https://github.com/rhysd/tui-textarea
pub fn render_component_editor_pane(
    frame: &mut Frame,
    work_state: &mut WorkState,
    _db_conn: &Connection,
    area: Rect,
    _selected_item: String,
) {
    // TODO fix this, it overwrites the

    let rows = Layout::default()
        .direction(Direction::Vertical)
        .constraints([
            Constraint::Length(3), // id row
            Constraint::Length(3), // name row
            Constraint::Length(5), // purpose row
            Constraint::Length(5), // summary row
        ])
        .split(area);

    render_component_detail_row(
        frame,
        rows[0],
        ComponentField::Id.label(),
        &work_state.component_text_areas.id,
    );
    render_component_detail_row(
        frame,
        rows[1],
        ComponentField::Name.label(),
        &work_state.component_text_areas.name,
    );
    render_component_detail_row(
        frame,
        rows[2],
        ComponentField::Purpose.label(),
        &work_state.component_text_areas.purpose,
    );
    render_component_detail_row(
        frame,
        rows[3],
        ComponentField::Summary.label(),
        &work_state.component_text_areas.summary,
    );
}

fn render_component_detail_row(
    frame: &mut Frame,
    area: Rect,
    label: &str,
    textarea: &TextArea<'_>,
) {
    let chunks = Layout::default()
        .direction(Direction::Horizontal)
        .constraints([
            Constraint::Length(10), // label column
            Constraint::Min(10),    // textarea column
        ])
        .split(area);

    let label_widget = Paragraph::new(label).style(Style::default().fg(Color::Yellow));
    frame.render_widget(label_widget, chunks[0]);

    frame.render_widget(textarea, chunks[1]);
}


// ----------------------------------------------------------------- Component text areas
// Originally generated by chatgpt
#[derive(Debug, Clone)]
pub struct ComponentTextAreas {
    pub id: TextArea<'static>,
    pub name: TextArea<'static>,
    pub purpose: TextArea<'static>,
    pub summary: TextArea<'static>,
    pub active_field: ComponentField,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ComponentField {
    Id,
    Name,
    Purpose,
    Summary,
}

impl ComponentField {
    pub fn next(self) -> Self {
        match self {
            ComponentField::Id => ComponentField::Name,
            ComponentField::Name => ComponentField::Purpose,
            ComponentField::Purpose => ComponentField::Summary,
            ComponentField::Summary => ComponentField::Id,
        }
    }

    pub fn previous(self) -> Self {
        match self {
            ComponentField::Id => ComponentField::Summary,
            ComponentField::Name => ComponentField::Id,
            ComponentField::Purpose => ComponentField::Name,
            ComponentField::Summary => ComponentField::Purpose,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            ComponentField::Id => "ID:",
            ComponentField::Name => "Name:",
            ComponentField::Purpose => "Purpose:",
            ComponentField::Summary => "Summary:",
        }
    }
}

impl ComponentTextAreas {
    pub fn new() -> Self {
        let mut id = TextArea::default();
        id.set_placeholder_text("Component ID (read-only)");
        id.set_style(Style::default().fg(Color::Gray)); // Read-only styling

        let mut name = TextArea::default();
        name.set_placeholder_text("Enter component name");
        name.set_style(Style::default().fg(Color::White));

        let mut purpose = TextArea::default();
        purpose.set_placeholder_text("Enter component purpose");
        purpose.set_style(Style::default().fg(Color::White));

        let mut summary = TextArea::default();
        summary.set_placeholder_text("Enter component summary");
        summary.set_style(Style::default().fg(Color::White));

        Self {
            id,
            name,
            purpose,
            summary,
            active_field: ComponentField::Name, // Start with name (skip read-only ID)
        }
    }

    pub fn get_active_textarea(&mut self) -> &mut TextArea<'static> {
        self.get_textarea(self.active_field)
    }

    pub fn get_textarea(&mut self, field: ComponentField) -> &mut TextArea<'static> {
        match field {
            ComponentField::Id => &mut self.id,
            ComponentField::Name => &mut self.name,
            ComponentField::Purpose => &mut self.purpose,
            ComponentField::Summary => &mut self.summary,
        }
    }

    pub fn active_field(&self) -> ComponentField {
        self.active_field
    }

    pub fn next_field(&mut self) {
        self.active_field = self.active_field.next();
        // Skip ID field in forward direction (it's read-only)
        if self.active_field == ComponentField::Id {
            self.active_field = ComponentField::Name;
        }
    }

    pub fn previous_field(&mut self) {
        self.active_field = self.active_field.previous();
        // Skip ID field in backward direction (it's read-only)
        if self.active_field == ComponentField::Id {
            self.active_field = ComponentField::Summary;
        }
    }

    pub fn set_field(&mut self, field: ComponentField) {
        // Don't allow setting focus to read-only ID field
        if field != ComponentField::Id {
            self.active_field = field;
        }
    }

    // Load component data into text areas
    pub fn load_component(&mut self, component: &Component) {
        self.id.delete_line_by_head();
        self.id.insert_str(component.id.to_string());

        self.name.delete_line_by_head();
        self.name.insert_str(&component.name);

        self.purpose.delete_line_by_head();
        self.purpose.insert_str(&component.purpose);

        self.summary.delete_line_by_head();
        self.summary.insert_str(&component.summary);
    }

    // Extract component data from text areas
    pub fn extract_component(&self) -> Component {
        Component {
            file_id: 0, // TODO populate.
            id: self.id.lines().join("").parse::<u64>().unwrap_or(0), // TODO panic if fail?
            name: self.name.lines().join("\n"),
            purpose: self.purpose.lines().join("\n"),
            summary: self.summary.lines().join("\n"),
            team_id: 0, // TODO populate.
        }
    }

    // Handle input for the active text area
    pub fn handle_input(&mut self, input: tui_textarea::Input) -> bool {
        // Don't allow editing the ID field
        if self.active_field == ComponentField::Id {
            return false;
        }

        let field_modified = self.get_active_textarea().input(input);
        field_modified
    }

    // Update visual styling based on active field
    pub fn update_styling(&mut self) {
        // Reset all to inactive style
        let inactive_style = Style::default().fg(Color::White);
        let active_style = Style::default()
            .fg(Color::Yellow)
            .add_modifier(Modifier::BOLD);
        let readonly_style = Style::default().fg(Color::Gray);

        self.id.set_style(readonly_style);
        self.name
            .set_style(if self.active_field == ComponentField::Name {
                active_style
            } else {
                inactive_style
            });
        self.purpose
            .set_style(if self.active_field == ComponentField::Purpose {
                active_style
            } else {
                inactive_style
            });
        self.summary
            .set_style(if self.active_field == ComponentField::Summary {
                active_style
            } else {
                inactive_style
            });

        // Update block borders
        let active_block = Block::default()
            .borders(Borders::ALL)
            .border_style(Style::default().fg(Color::Blue));
        let inactive_block = Block::default()
            .borders(Borders::ALL)
            .border_style(Style::default().fg(Color::Gray));
        let readonly_block = Block::default()
            .borders(Borders::ALL)
            .border_style(Style::default().fg(Color::DarkGray));

        self.id
            .set_block(readonly_block.clone().title("ID (read-only)"));
        self.name
            .set_block(if self.active_field == ComponentField::Name {
                active_block.clone().title("Name")
            } else {
                inactive_block.clone().title("Name")
            });
        self.purpose
            .set_block(if self.active_field == ComponentField::Purpose {
                active_block.clone().title("Purpose")
            } else {
                inactive_block.clone().title("Purpose")
            });
        self.summary
            .set_block(if self.active_field == ComponentField::Summary {
                active_block.clone().title("Summary")
            } else {
                inactive_block.clone().title("Summary")
            });
    }
}
